(fset 'table_calc
      "Gkkkkkkk\C-c\C-cj\C-c\C-cj\C-c\C-cj\C-c\C-cj\C-c\C-cj\C-c\C-cj\C-c\C-c")
(fset 'table-new-line
   [?o ?| ?| ?\C-u ?\M-! ?e ?c ?h ?o ?  ?- ?n ?  ?\' backspace ?` ?d ?a ?t ?e ?  ?\' ?+ ?% ?m ?- ?% ?d ?\' ?` return tab])

(defun table_calc_func ()
  (interactive)
  (point-to-register ?r)
  (end-of-buffer)
  (previous-line)
  (previous-line)
  (previous-line)
  (previous-line)
  (previous-line)
  (previous-line)
  (org-ctrl-c-ctrl-c)
  (next-line)
  (org-ctrl-c-ctrl-c)
  (next-line)
  (org-ctrl-c-ctrl-c)
  (next-line)
  (org-ctrl-c-ctrl-c)
  (next-line)
  (org-ctrl-c-ctrl-c)
  (next-line)
  (org-ctrl-c-ctrl-c)
  (jump-to-register ?r))

(spacemacs/set-leader-keys "o t c" 'table_calc_func)
(spacemacs/set-leader-keys "o t n l" 'table-new-line)
(provide 'my-macro)
